# Generated by Django 4.0.1 on 2023-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildberriesProduct',
            fields=[
                ('article', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
